Ingress default values
cloudfoundry-incubator/fissile pull request #491
Opened 2019-04-10 20:56 UTC by f0rmiga

## Description

- Added ingress default values with comments.
- Updated values_test.go.

## Test plan

Fissile should generate the `values.yaml` with the specified ingress default values (as seen on the unit test).

2019-04-11 20:39 UTC, mook-as approved these changes
Generally okay, probably better to split out unrelated cleanup though :(

2019-04-11 20:39 UTC, mook-as commented on kube/values.go
> +	values.Add("ingress", ingress.Sort())
Testing out inlining this…

```golang
	values.Add("ingress", helm.NewMapping(
		"annotations", helm.NewNode(map[string]interface{}{}, helm.Comment("ingress.annotations allows specifying custom ingress annotations that gets merged to the default annotations.")),
		"enabled", helm.NewNode(false, helm.Comment("ingress.enabled enables ingress support - working ingress controller necessary.")),
		"tls", helm.NewNode(map[string]interface{}{}, helm.Comment("ingress.tls.crt and ingress.tls.key, when specified, are used by the TLS secret for the Ingress resource.")),
	).Sort())
```

Hmm, not sure I like one better than the other.

2019-04-11 21:00 UTC, f0rmiga commented on kube/values.go
> +	values.Add("ingress", ingress.Sort())
I rarely prefer this type of reduction. In this case I'm ok with either.

2019-04-12 22:57 UTC, mook-as requested changes
https://github.com/cloudfoundry-incubator/fissile/blob/e67442aada507ce1b9e6c45bef44dec6dca876bd/kube/utils.go#L219 needs to remove `services.ingress` (or possibly move the whole new part in there).

2019-04-15 20:45 UTC, mook-as approved these changes

2019-04-15 20:45 UTC, merged