Adding a flag to display image name
cloudfoundry-incubator/fissile pull request #509
Opened 2019-08-02 22:35 UTC by bikramnehra

## Description

This PR is to introduce a new flag `--show-image-name` in `fissile build release-images` which will display image name along with tag without actually building it.

## Test plan

Pass `--show-image-name=true` while building fissile release image and verify if it displays image name and exits immediately.

2019-08-02 22:54 UTC, f0rmiga requested changes

2019-08-02 22:54 UTC, f0rmiga commented on builder/release_image.go
> +	ShowImageName          bool
`--display-image-name` sounds more natural.

2019-08-02 22:54 UTC, f0rmiga commented on builder/release_image.go
> +			return nil
Instead of returning here, I'd add another flag `--no-run` and then return `nil` if it is set after this `condition`.

2019-08-02 23:32 UTC, f0rmiga commented
It has been decided over a private channel that we want this functionality as a separate subcommand rather than a flag.

2019-08-06 23:07 UTC, bikramnehra commented
It is finally decided to introduce a `--dry-run` flag which will skip the build part. Also, name of the image to be built will always be printed.

2019-08-06 23:07 UTC, f0rmiga approved these changes

2019-08-06 23:14 UTC, merged