Pod startup ordering
cloudfoundry-incubator/fissile pull request #525
Opened 2019-11-15 23:54 UTC by jandubois

# Implement configgin startup synchronization

The next version of configgin will export bosh properties to a secret and tag it with the value of `CONFIGGIN_VERSION_TAG` (the helm chart version plus the secrets rotation count).

Fissile now defines an environment variable that references that role's secret tag in each role that needs to import links from it. This has the effect of delaying startup of the pod until all links that have to be imported have been written to their corresponding secrets.

# Implement `ignore` option for link consumers

In the rolemanifest a job can now explicitly state that a specified bosh link will *not* be consumed:

```
      jobs:
      - name: sample-job
        release: sample
        consumes:
          not-used: {ignore: true}
```

The link definition will not be included in the job information passed on to Configgin, so the link will not resolve at runtime. It is the responsibility of the templates to not reference it (by setting properties, or by patching the templates).

Note that this feature allows ignoring of non-optional links as well!

2019-11-18 21:48 UTC, andreas-kupries requested changes
Just comment nits. Code LGTM.

2019-11-18 21:48 UTC, andreas-kupries commented on model/instance_groups.go
> +// Manifest return a reference to the instance groups role manifest
`return` --> `returns` (+ `s`).

2019-11-18 21:48 UTC, andreas-kupries commented on test-assets/role-manifests/kube/volumes.yml
> +# The provider role only exist so that TestPodGetEnvVarsConfiggin can use
`exists`

2019-11-18 21:48 UTC, andreas-kupries commented on test-assets/role-manifests/kube/volumes.yml
> +# it to reference in a mock up bosh link.
`to` -> `as` ? (Or remove `in` ?)

2019-11-18 22:05 UTC, jandubois commented on model/instance_groups.go
> +// Manifest return a reference to the instance groups role manifest
Addressed by fdbaeda

2019-11-18 22:05 UTC, jandubois commented on test-assets/role-manifests/kube/volumes.yml
> +# it to reference in a mock up bosh link.
Addressed by fdbaeda

2019-11-18 22:06 UTC, jandubois commented on test-assets/role-manifests/kube/volumes.yml
> +# The provider role only exist so that TestPodGetEnvVarsConfiggin can use
Addressed by fdbaeda

2019-11-18 22:11 UTC, andreas-kupries approved these changes
LGTM.

2019-11-18 22:18 UTC, andreas-kupries commented
Not merging yet, wait for `configgin` to be ready as well. Must be kept in close sync.

2019-11-21 18:43 UTC, andreas-kupries approved these changes
LGTM

2019-11-22 01:59 UTC, merged